In [ ]:
#importing all the libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [ ]:
#Reading the csv file
df=pd.read_csv("/content/Crop_recommendation.csv")
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [ ]:
#Here X denotes the input variables for the model and y denotes the target varibale
x = df[['temperature', 'ph', 'rainfall', 'label']]
y = df[['humidity']]

In [ ]:
x.head()

   temperature        ph    rainfall label
0    20.879744  6.502985  202.935536  rice
1    21.770462  7.038096  226.655537  rice
2    23.004459  7.840207  263.964248  rice
3    26.491096  6.980401  242.864034  rice
4    20.130175  7.628473  262.717340  rice

In [ ]:
y.head()

    humidity
0  82.002744
1  80.319644
2  82.320763
3  80.158363
4  81.604873

In [ ]:
ct = ColumnTransformer([
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False), ['label']),
    ('scaler', StandardScaler(), ['temperature','ph','rainfall'])
])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1760, 4), (440, 4), (1760, 1), (440, 1))

In [ ]:
pipeline=Pipeline([
    ('preprocessor', ct),
    ('model', LinearRegression())
])
pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['label']),
                                                 ('scaler', StandardScaler(),
                                                  ['temperature', 'ph',
                                                   'rainfall'])])),
                ('model', LinearRegression())])

In [ ]:
y_pred=pipeline.predict(x_test)

In [ ]:
print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

R2 Score: 0.9621957381323745
MAE: 2.865703005959152
MSE: 16.009355377800347

In [ ]:
input_data = pd.DataFrame({
    'temperature': [30],
    'ph': [6.6],
    'rainfall': [202.9],
    'label': ['corn']
})

prediction = pipeline.predict(input_data)

print("Predicted Humidity:", prediction[0])

Predicted Rainfall: [76.97211687]

In [ ]:
import joblib
joblib.dump(pipeline, "humidity.pkl")

['humidity.pkl']